@extends('layouts.app')

@section('title', 'Nouvelle consultation')
@section('page-title', 'Nouvelle consultation')
@section('page-subtitle', 'Enregistrer un passage a l infirmerie')

@section('content')
@php
    $studentOptions = $enrollments->map(fn ($enrollment) => ['id' => $enrollment->student_id, 'name' => $enrollment->student?->full_name, 'class_name' => $enrollment->classGroup?->full_name, 'age' => $enrollment->student?->date_of_birth?->age, 'gender' => $enrollment->student?->gender, 'phone' => $enrollment->student?->guardian_phone ?: ($enrollment->student?->father_phone ?: $enrollment->student?->mother_phone)])->values();
@endphp
<div class="px-0 pb-12" x-data="{ query: '', studentId: '{{ old('student_id') }}', selected: null, open: false, students: @js($studentOptions), init() { this.selected = this.students.find(student => String(student.id) === String(this.studentId)) || null; this.query = this.selected?.name || ''; }, matches() { const query = this.query.trim().toLowerCase(); return query.length < 2 ? [] : this.students.filter(student => (student.name + ' ' + student.class_name).toLowerCase().includes(query)).slice(0, 8); }, choose(student) { this.selected = student; this.studentId = student.id; this.query = student.name; this.open = false; } }">
    <div class="mb-5 flex items-center gap-3"><a href="{{ route('infirmary.index') }}" class="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50" aria-label="Retour"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg></a><p class="text-sm text-gray-500">{{ $academicYearLabel }}</p></div>
    @if(! $activeYear || $enrollments->isEmpty())
        <div class="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Une annee scolaire active et des eleves inscrits sont necessaires pour enregistrer une consultation.</div>
    @else
        <form method="POST" action="{{ route('infirmary.visits.store') }}" class="w-full rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-7">@csrf
            <div class="mb-7 border-b border-gray-100 pb-4"><h2 class="text-lg font-bold text-gray-900">Informations de la consultation</h2><p class="mt-1 text-sm text-gray-500">Recherchez un eleve par son nom ou sa classe, puis renseignez les parametres et les soins.</p></div>
            <input type="hidden" name="student_id" x-model="studentId">
            <div class="grid grid-cols-1 gap-5 lg:grid-cols-12"><div class="relative lg:col-span-5"><label class="mb-1.5 block text-sm font-semibold text-gray-700">Eleve <span class="text-red-500">*</span></label><input type="search" x-model="query" @input="studentId = ''; selected = null; open = true" @focus="open = true" @keydown.escape="open = false" placeholder="Commencez a saisir un nom ou une classe" autocomplete="off" class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100"><div x-show="open && matches().length" x-cloak @click.outside="open = false" class="absolute z-20 mt-1 max-h-64 w-full overflow-y-auto rounded-xl border border-gray-200 bg-white p-1 shadow-xl"><template x-for="student in matches()" :key="student.id"><button type="button" @click="choose(student)" class="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left hover:bg-sky-50"><span><span class="block text-sm font-semibold text-gray-800" x-text="student.name"></span><span class="block text-xs text-gray-500" x-text="student.class_name"></span></span><span class="text-xs text-gray-400" x-text="student.gender === 'F' ? 'F' : 'M'"></span></button></template></div>@error('student_id')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="lg:col-span-2"><label class="mb-1.5 block text-sm font-semibold text-gray-700">Date <span class="text-red-500">*</span></label><input type="date" name="visit_date" value="{{ old('visit_date', now()->toDateString()) }}" required class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100"></div><div class="lg:col-span-2"><label class="mb-1.5 block text-sm font-semibold text-gray-700">Heure <span class="text-red-500">*</span></label><input type="time" name="visit_time" value="{{ old('visit_time', now()->format('H:i')) }}" required class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100"></div><div class="lg:col-span-3"><label class="mb-1.5 block text-sm font-semibold text-gray-700">Temperature (C)</label><input type="number" name="temperature" value="{{ old('temperature') }}" min="30" max="45" step="0.1" placeholder="Ex: 37.2" class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100">@error('temperature')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div class="lg:col-span-12 grid grid-cols-1 gap-3 rounded-xl border border-sky-100 bg-sky-50/50 p-4 sm:grid-cols-4" x-show="selected" x-cloak><div><p class="text-xs font-semibold uppercase tracking-wide text-sky-700">Classe</p><p class="mt-1 text-sm font-semibold text-gray-800" x-text="selected?.class_name || '-'"></p></div><div><p class="text-xs font-semibold uppercase tracking-wide text-sky-700">Age</p><p class="mt-1 text-sm font-semibold text-gray-800"><span x-text="selected?.age ?? '-'"></span> ans</p></div><div><p class="text-xs font-semibold uppercase tracking-wide text-sky-700">Sexe</p><p class="mt-1 text-sm font-semibold text-gray-800" x-text="selected?.gender === 'F' ? 'Feminin' : 'Masculin'"></p></div><div><p class="text-xs font-semibold uppercase tracking-wide text-sky-700">Parent</p><p class="mt-1 text-sm font-semibold text-gray-800" x-text="selected?.phone || 'Non renseigne'"></p></div></div>
                <div class="lg:col-span-6"><label class="mb-1.5 block text-sm font-semibold text-gray-700">Motif de la visite <span class="text-red-500">*</span></label><textarea name="visit_reason" rows="5" required class="w-full resize-y rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100">{{ old('visit_reason') }}</textarea>@error('visit_reason')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="lg:col-span-6"><label class="mb-1.5 block text-sm font-semibold text-gray-700">Traitement effectue</label><textarea name="treatment" rows="5" class="w-full resize-y rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100">{{ old('treatment') }}</textarea></div><div class="lg:col-span-12 flex justify-end gap-3"><a href="{{ route('infirmary.index') }}" class="rounded-xl border border-gray-200 px-5 py-2.5 text-sm font-semibold text-gray-600 hover:bg-gray-50">Annuler</a><button type="submit" :disabled="!studentId" class="inline-flex items-center gap-2 rounded-xl bg-sky-700 px-5 py-2.5 text-sm font-bold text-white transition hover:bg-sky-800 disabled:cursor-not-allowed disabled:opacity-50"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>Enregistrer la consultation</button></div>
            </div>
        </form>
    @endif
</div>
@endsection
